### PR TITLE
Update plugin.php

### PR DESCRIPTION
**Pull request by der-martin85**
changed context in moodle 4.2

### CODE REVIEW

**Comment by Syxton** [comment]
@der-martin85 @ChaoticDalo verified that this fixes 4.2 issue of nothing showing in the block

**Comment by aspark21** [comment]
still seems to be broken with this fix applied as far as I can see

**Comment by aspark21** [comment]
can this be merged?

**Comment by ChaoticDalo** [comment]
Thank you @der-martin85 for finding and fixing this. This change can be found in the master or release/MOODLE_421_STABLE branch.

**Pull request closed without merging**
